
---
- hosts: all
  become: true

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"





Command = ansible-playbook -i inventory.ini ec2_shutdown.yaml --vault-password-file vault.pass
